### PR TITLE
Use AA+ 2.44, with necessary modifications

### LINKED ISSUE #110: calculation of 2023 spring equinox is off by over 1:30
Thank you for this great library.  It's been super helpful.

I'm calculating equinoxes and solstices with SwiftAA and noticing over a minute and a half difference from various sources on the internet.  For example, most sources say it will be at 21:24, but SwiftAA calculates it as 21:25:34.
Is this degree of inaccuracy normal for this library?
I'm curious if this is due to being out of date with the AA+ library which is up to v2.43 in 2022, whereas we're still using a the 2.0.9 version from 2019?  Would it be much work to update AA+ to the newest version?  I noticed in the change logs that various renames happened.  Does this affect ObjCAA?

### PR DESCRIPTION
**Pull request by vincentneo**
~Not tested.~ Did ran SwiftAATests, 7 failing out of 197.
Do note that `KPCAAElliptical` now has Pluto commented out, as its removed from `AAElliptical`.

Maybe fixes #110

### CODE REVIEW

**Comment by onekiloparsec** [comment]
Thanks a lot for this large and great pull request! I'll have a look asap this week-end!

**Comment by onekiloparsec** [comment]
@vincentneo please allow me to write on your branch. Your PR is helping fixing a few things along the way, that's really cool (I am reviewing all the failing tests, fixing one after the other).

**Comment by onekiloparsec** [comment]
That's it, I've all tests green again.

**Comment by vincentneo** [comment]
> @vincentneo please allow me to write on your branch. 

btw, do I need to do anything to allow write access?

**Comment by onekiloparsec** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by onekiloparsec** [comment]
Well I don't know if you did something. On my side, not completely sure of how to use the GitHub CLI, I nonetheless tried to push my changes to that PR and tadaaa, here there are. Hence, I can now merge. And I will make a release right after it.

**Comment by vincentneo** [comment]
I haven’t had the chance to do anything just now, so I guess it does work by itself after all :)

**Comment by onekiloparsec** [comment]
Well, PR is merged, thanks you very much. However, I am just unable to make a CocoaPod release for now. Too many cryptic compilation errors. Even the command `swift test` doesn't work. I am playing updating the Package.swift file, but to no avail.

**Comment by onekiloparsec** [comment]
It seems the AA+ author updated some stuff. One needs to investigate how he changed his way of compiling... What I don't understand is that Xcode is able to compile and run the tests. Yet, impossible to go beyond that.

**Comment by vincentneo** [comment]
@onekiloparsec 

I had to change ObjCAA to compile using C++ 17 because of a change in AA+.

In `AAVSOP87D_EAR.cpp`, 
> PJN / 22-04-2020 1. Reworked C arrays to use std::array.

I believe this change, which uses `constexpr`, required it to be compiled using C++ 17, at least when I couldn't compile it, I searched around and C++ 17 seemed to be the solution as it worked. (I am not a C/C++ developer)

Screenshot 2022-07-25 at 10 47 39 PM

My guess is `swift test` internally compiles C++ code at a lower C++ dialect, hence failure, and CocoaPods is just using the default behaviour.

This change in this answer may help in CocoaPods deployment, if the C++ issue is the reason: https://stackoverflow.com/a/63233322

**Comment by onekiloparsec** [comment]
Still struggling a bit (pod spec lint still fails). I'll be off in vacations for a week, and I'll restart right after that.

**Comment by vincentneo** [comment]
I just realised you haven't created a release (2.4.0) on GitHub, maybe its that.
(in case if the lint error was due to `fatal: Remote branch 2.4.0 not found in upstream origin`)

Anyways, just ignore this and enjoy your vacation first! I am just leaving this comment down, in case I forget in a week's time.

**Pull request merged**
