### PR TITLE
Immutable NumericType.value

### PR DESCRIPTION
**Pull request by alex-vasenin**
see issue #16

### CODE REVIEW

**Comment by alex-vasenin** [comment]
I added one more commit which moves conformance to ExpressibleBy*Literal to NumericType itself. Implementation a bit awkward, but I think it's best available solution.

**Comment by onekiloparsec** [comment]
Nice work. But could you explain why you used a kind of private protocol `_NumericType` and left the other one intentionally blank?

As for the JulianDay, you choose to store a `_date` var that could be actually created on the fly on the `date()` method. But given that the thing is immutable, there is no reason for not storing such date. Am I correct?

**Comment by alex-vasenin** [comment]
Hi Cédric! The idea of the last commit if to conform to DRY principle. However, I wasn't be able to find a way for protocol _to conform to other protocol_ *and* _provide a default implementation_ at the same time. It looks like it's impossible with Swift 3.0.1, so `_NumericType` provides default implementation and `NumericType` declares conformance. A bit awkward, I agree.

**Comment by alex-vasenin** [comment]
As for the `_date` variable, I suppose it (probably) might be useful later, though I'm not sure about it.

**Comment by onekiloparsec** [comment]
Thanks for the input. I've tried on my side, and indeed, if you try to put both the conformance and the default implementation you get strange errors, about Double and inits. Anyway, that's piece of work is an improvement anyway.

**Pull request merged**
